# Use the official Node.js image as the base image
FROM node:20.5.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY LoggerBackEnd .

# Install dependencies
RUN npm install

# Copy the rest of the application files

# Expose the port the app runs on
EXPOSE 3005

# Command to run the application
CMD ["npm", "start"]