version: '3.8'

services:
  react-app:
    image: react-app:latest

    ports:
      # - "3000:3000"
      - "80:80"
      - "443:443"
      - "3011:3000"
    depends_on:
      - python-app
    networks:
      - app-network
  logger-app:
     image: logger-app:latest
     ports:
       - "3005:3005"
     depends_on:
       - react-app
     networks:
       - app-network
  python-app:
    image: python-app

    ports:
      - "3001:3001"
      - "3002:3002"
      - "8000:8000"
      - "9001:9001"
    depends_on:
      - db
    networks:
      - app-network
      
  report-app:
    image: report-app

    ports:
      - "9004:9004"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql-app:latest
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - master-data:/var/lib/mysql
      # - /home/abhishek/mysql-slave/conf/:/etc/mysql/conf.d
  postgres:
    image: postgres-app
    ports:
      - "5433:5432"
    
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #- /home/merwin/Hyphenview_Updated_Code/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  
  redis:
    image: redis:latest
    command: redis-server --requirepass "Admin123*"
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  master-data:
  postgres-data: