FROM postgres:15

# Copy the SQL scripts to initialize the database
COPY pgbackup.dump /docker-entrypoint-initdb.d/
COPY procedures.sql /docker-entrypoint-initdb.d/
COPY restore-dump.sh /docker-entrypoint-initdb.d/

# Make the script executable
RUN chmod +x /docker-entrypoint-initdb.d/restore-dump.sh

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=Admin123*
ENV POSTGRES_DB=hyphenview_new

# Expose the PostgreSQL port
EXPOSE 5432